Arc 78 trajectory follower integration
usdot-fhwa-stol/autoware.auto pull request #26
Opened 2024-07-26 21:06 UTC by saina-ramyar

# PR Details
## Description

This PR is part of the integration testing of the Trajectory Follower Wrapper on a physical vehicle. 
Related PR:
https://github.com/usdot-fhwa-stol/carma-platform/pull/2419

## Related GitHub Issue

## Related Jira Key

https://usdot-carma.atlassian.net/browse/ARC-78

## Motivation and Context

Integrate the Trajectory Follower controller of Autoware, that has a MPC based lateral controller, to improve vehicle's performance.
## How Has This Been Tested?
Integration tested on Blue Lexus

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-08-15 15:28 UTC, MishkaMN requested changes
Looks like 2 nodes added were from autoware, so I really didn't look at them. 
Please let me know if there are specific lines that you added that need review. 
It looks like we may be missing last commit because debug prints are still here, so I can look at it after they are removed.

2024-08-15 15:28 UTC, MishkaMN commented on AutowareAuto/src/control/trajectory_follower/src/mpc_utils.cpp
> +  const float64_t my_yaw = 0.0; //tf2::getYaw(self_pose.orientation);
Is this correct? or did we forget to push commit.
If it is actually correct, let's explain why it needs to be this way.

2024-08-15 15:28 UTC, MishkaMN commented on AutowareAuto/src/control/trajectory_follower/src/mpc_utils.cpp
> +    std::cerr<< "dist_squared:  "<<dist_squared<<std::endl;
after the integration is done, it is probably better to remove these cerr prints, because I imagine they will be printing at 30hz which is too much.

2024-08-15 15:28 UTC, MishkaMN commented on AutowareAuto/src/control/trajectory_follower_nodes/src/lateral_controller_node.cpp
> +  rcutils_ret_t ret = rcutils_logging_set_logger_level("trajectory_follower", RCUTILS_LOG_SEVERITY_DEBUG);
debug prints should be removed

2024-08-16 18:11 UTC, saina-ramyar commented
> Looks like 2 nodes added were from autoware, so I really didn't look at them. Please let me know if there are specific lines that you added that need review. It looks like we may be missing last commit because debug prints are still here, so I can look at it after they are removed.

I only added one node (longitudinal_controller), there rest already existed. Also haven't made any logic changes, just adding some debug logs which were left and removed now. You can review again.

2024-08-16 19:07 UTC, MishkaMN commented on AutowareAuto/src/control/trajectory_follower_nodes/src/lateral_controller_node.cpp
> +  }
we should remove this debugging because it is forcing "trajectory_follower" logger to be DEBUG.

2024-08-16 19:43 UTC, adev4a approved these changes

2024-08-19 23:42 UTC, MishkaMN approved these changes
Looks good to me. CI is failing due to not enough memory available. 
https://github.com/soedinglab/hh-suite/issues/280
We can probably merge this.

2024-08-28 18:53 UTC, merged